### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by sandeepjella** [LLNL/zero-rk#3]
Hello, thanks for making this available.

I am trying to install Zero-rk in Ubuntu with gcc 9 

I get a compiler error when the build starts on the applications - any advice? I don't think anything is wrong with the code itself but perhaps am missing some library or dependency? 

I also tried make -i to see if I could step over the obstacle but every application results in the same "undefined reference to.." as below.

Many thanks,

Sandeep.

[ 35%] Built target thermo_check.x
[ 38%] Built target constVolumeWSR_yml.x
[ 41%] Built target constVolumeWSR_mpi.x
[ 43%] Built target constVolumeWSR.x
[ 45%] Built target constVolumeWSR_mpi_yml.x
[ 50%] Built target perturbAFactor_serial.x
[ 53%] Built target perturbAFactor_mpi.x
[ 57%] Built target perturbAFactorGSA_mpi.x
[ 61%] Built target idt_diagnostic.x
[ 61%] Linking CXX executable variable_volume.x

```
CMakeFiles/variable_volume.x.dir/user_functions.cpp.o: In function `UserData::BuildInitialState()':
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:349: undefined reference to `VariableVolumeIFP::initComp[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:350: undefined reference to `VariableVolumeIFP::initComp[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:374: undefined reference to `VariableVolumeIFP::compType[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:388: undefined reference to `VariableVolumeIFP::compType[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:390: undefined reference to `VariableVolumeIFP::compType[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:377: undefined reference to `VariableVolumeIFP::thermFile[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:376: undefined reference to `VariableVolumeIFP::mechFile[abi:cxx11]() const'
CMakeFiles/variable_volume.x.dir/user_functions.cpp.o: In function `UserData::UserData(char const*)':
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:201: undefined reference to `VariableVolumeIFP::VariableVolumeIFP(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:211: undefined reference to `VariableVolumeIFP::volumeInterpolationMethod[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:214: undefined reference to `VariableVolumeIFP::volumeInterpolationMethod[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:219: undefined reference to `VariableVolumeIFP::volumeFile[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:225: undefined reference to `VariableVolumeIFP::mechFile[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:226: undefined reference to `VariableVolumeIFP::thermFile[abi:cxx11]() const'
/home/sandeep/zero-rk/applications/variable_volume/user_functions.cpp:227: undefined reference to `VariableVolumeIFP::mechLogFile[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
applications/variable_volume/CMakeFiles/variable_volume.x.dir/build.make:195: recipe for target 'applications/variable_volume/variable_volume.x' failed
make[2]: *** [applications/variable_volume/variable_volume.x] Error 1
CMakeFiles/Makefile2:1662: recipe for target 'applications/variable_volume/CMakeFiles/variable_volume.x.dir/all' failed
make[1]: *** [applications/variable_volume/CMakeFiles/variable_volume.x.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by whitesides1** [comment]
Hi Sandeep,

This looks to me like you might have used two different compilers at different stages when building.  It could also be an issue with cmake not passing the right compiler flags.  Can you try to build again from a clean build directory?  What version of cmake are you using?  (Also, please use `code` formatting when pasting in error logs so it doesn't get mangled by the markdown processor).

-r

**Comment by sandeepjella** [comment]
Will do! thanks for the quick response, I'll write back shortly. Yes, I did have a dirty start since a number of things were missing in my laptop.

Sandeep.

**Comment by sandeepjella** [comment]
Russel - it installed perfectly now. I simply removed the entire directory and re-started. There were a bunch of warnings but mostly the compiler turning its nose up at a few things. I can paste the logfile if you really need it.

Again, thanks for letting us all benefit from your work. Eager to try it now on some real work!

- Sandeep.

**Comment by whitesides1** [comment]
Some warnings are to be expected.  Please make sure the examples will run for you and I will close out this issue.

**Comment by sandeepjella** [comment]
Works excellent, I was able to run all the examples I was interested in and now able to setup my own stuff.

**Comment by whitesides1** [comment]
Excellent!  Glad you got it up and running.
